-- =============================================================================
-- HYPRLAND CONFIGURATION (Lua 5.5.0 Compliant)
-- Optimized for Lenovo ThinkPad E14 Gen 7 (AMD)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Hardware & Environment Initialization
-- -----------------------------------------------------------------------------
hl.env("LIBVA_DRIVER_NAME", "radeonsi")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- -----------------------------------------------------------------------------
-- 2. Monitor Setup & Screen Scaling
-- -----------------------------------------------------------------------------
hl.monitor("eDP-1", "preferred", "auto", "1.25")
hl.monitor(",", "preferred", "auto", "1")

-- -----------------------------------------------------------------------------
-- 3. Automatic Startup Daemons
-- -----------------------------------------------------------------------------
hl.exec_once("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
hl.exec_once("systemctl --user start hyprpolkitagent")
hl.exec_once("hyprlauncher --daemon")

-- -----------------------------------------------------------------------------
-- 4. Unified Desktop Configuration Structure
-- -----------------------------------------------------------------------------
hl.config({
    -- Explicitly opt-out of the example banner
    autogenerated = false,

    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
        }
    },

    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        col_active_border = "rgba(33ccffee) rgba(00ff99ee) 45deg",
        col_inactive_border = "rgba(595959aa)",
        layout = "dwindle",
    },

    decoration = {
        rounding = 6,
        blur = {
            enabled = false, -- Disabled to optimize AMD laptop battery
        },
        shadow = {
            enabled = false,
        }
    },

    animations = {
        enabled = true,
        bezier = { "myBezier", "0.05, 0.9, 0.1, 1.05" },
        animation = {
            { "windows", "1, 5, myBezier" },
            { "workspaces", "1, 4, default" }
        }
    }
})

-- -----------------------------------------------------------------------------
-- 5. Core Keybindings
-- -----------------------------------------------------------------------------
-- Format: hl.bind("MODS + KEY", DISPATCHER, OPTIONS_TABLE)
hl.bind("SUPER + Q", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + R", hl.dsp.exec_cmd("hyprlauncher --toggle"))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + M", hl.dsp.exit())
hl.bind("SUPER + V", hl.dsp.window.toggle_floating())

-- Focus Movement Keybindings (Vim navigation keys)
hl.bind("SUPER + h", hl.dsp.window.move_focus("l"))
hl.bind("SUPER + l", hl.dsp.window.move_focus("r"))
hl.bind("SUPER + k", hl.dsp.window.move_focus("u"))
hl.bind("SUPER + j", hl.dsp.window.move_focus("d"))

-- Workspace Switching Shortcuts (Looping logic perfectly valid in Lua 5.5)
for i = 1, 5 do
    local str_i = tostring(i)
    hl.bind("SUPER + " .. str_i, hl.dsp.workspace.go(str_i))
    hl.bind("SUPER + SHIFT + " .. str_i, hl.dsp.window.move_to_workspace(str_i))
end

-- -----------------------------------------------------------------------------
-- 6. ThinkPad Hardware Functional Keys (Fn)
-- -----------------------------------------------------------------------------
-- Audio Control (Using locked flag to enable use on lockscreens)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })

-- Backlight Control (Using both locked and repeating flags)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })
