-- =============================================================================
-- HYPRLAND CONFIGURATION (Official Lua API Compliant)
-- Optimized for Lenovo ThinkPad E14 Gen 7 (AMD)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. User Color Customization Palette (Constants)
-- -----------------------------------------------------------------------------
-- Formatted as standard hex integers: 0xAARRGGBB (Alpha, Red, Green, Blue)
local COLOR_BORDER_ACTIVE_START = "0xee33ccff" -- Sharp Cyan
local COLOR_BORDER_ACTIVE_END   = "0xee00ff99" -- Emerald Green
local COLOR_BORDER_INACTIVE     = "0xaa595959" -- Muted Slate Gray

-- -----------------------------------------------------------------------------
-- 1. Hardware & Environment Initialization
-- -----------------------------------------------------------------------------
hl.env("LIBVA_DRIVER_NAME", "radeonsi")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- -----------------------------------------------------------------------------
-- 2. Monitor Setup & Screen Scaling
-- -----------------------------------------------------------------------------
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1.25 })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- -----------------------------------------------------------------------------
-- 3. Automatic Startup Daemons
-- -----------------------------------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hyprlauncher -d")
end)

-- -----------------------------------------------------------------------------
-- 4. Desktop Configuration Matrix
-- -----------------------------------------------------------------------------
hl.config({
    autogenerated = false,

    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
        }
    },

    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        
        -- Plural "colors" array matching the underlying C++ schema rules
        col = {
            active_border = {
                colors = { COLOR_BORDER_ACTIVE_START, COLOR_BORDER_ACTIVE_END }
            },
            inactive_border = COLOR_BORDER_INACTIVE,
        },
        layout = "dwindle",
    },

    decoration = {
        rounding = 6,
        blur = {
            enabled = false, -- Disables background transparency rendering to maximize battery
        },
        shadow = {
            enabled = false,
        }
    },

    animations = {
        enabled = true,
        bezier = { "myBezier", "0.05, 0.9, 0.1, 1.05" },
        animation = {
            { "windows", "1, 5, myBezier" },
            { "workspaces", "1, 4, default" }
        }
    }
})

-- -----------------------------------------------------------------------------
-- 5. Core Keybindings
-- -----------------------------------------------------------------------------
hl.bind("SUPER + Q", function() hl.dispatch(hl.dsp.window.exec("kitty")) end)
hl.bind("SUPER + R", function() hl.dispatch(hl.dsp.window.exec("hyprlauncher --toggle")) end)
hl.bind("SUPER + C", function() hl.dispatch(hl.dsp.window.close()) end)
hl.bind("SUPER + M", function() hl.dispatch(hl.dsp.exit()) end)
hl.bind("SUPER + V", function() hl.dispatch(hl.dsp.window.float({ action = "toggle" })) end)

-- Vim Navigation Movement Keys
hl.bind("SUPER + h", function() hl.dispatch(hl.dsp.window.move_focus("l")) end)
hl.bind("SUPER + l", function() hl.dispatch(hl.dsp.window.move_focus("r")) end)
hl.bind("SUPER + k", function() hl.dispatch(hl.dsp.window.move_focus("u")) end)
hl.bind("SUPER + j", function() hl.dispatch(hl.dsp.window.move_focus("d")) end)

-- Workspace Navigation (1-5 Matrix Loop)
for i = 1, 5 do
    local ws_str = tostring(i)
    hl.bind("SUPER + " .. ws_str, function() hl.dispatch(hl.dsp.workspace.go(ws_str)) end)
    hl.bind("SUPER + SHIFT + " .. ws_str, function() hl.dispatch(hl.dsp.window.move_to_workspace(ws_str)) end)
end

-- -----------------------------------------------------------------------------
-- 6. ThinkPad Hardware Function Keys (Fn Buttons)
-- -----------------------------------------------------------------------------
-- Audio Mapping
hl.bind("XF86AudioMute", function() hl.dispatch(hl.dsp.window.exec("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")) end)
hl.bind("XF86AudioRaiseVolume", function() hl.dispatch(hl.dsp.window.exec("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+")) end)
hl.bind("XF86AudioLowerVolume", function() hl.dispatch(hl.dsp.window.exec("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")) end)

-- Screen Brightness Mapping
hl.bind("XF86MonBrightnessUp", function() hl.dispatch(hl.dsp.window.exec("brightnessctl set +5%")) end)
hl.bind("XF86MonBrightnessDown", function() hl.dispatch(hl.dsp.window.exec("brightnessctl set 5%-")) end)
